<script setup lang="ts">
import {computed,onMounted} from 'vue'
import GroupCard from '../components/GroupCard.vue'
import {useTournamentStore} from '../stores/tournament'
const s=useTournamentStore()
const upcoming=computed(()=>s.matches.filter(match=>match.status!=='FINISHED').sort((a,b)=>(a.kickoffAt?new Date(a.kickoffAt).getTime():Number.MAX_SAFE_INTEGER)-(b.kickoffAt?new Date(b.kickoffAt).getTime():Number.MAX_SAFE_INTEGER)).slice(0,8))
const results=computed(()=>s.matches.filter(match=>match.status==='FINISHED').slice(-8).reverse())
const dateTime=(value:string|null|undefined)=>value?new Date(value).toLocaleString('th-TH',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}):'รอกำหนดเวลา'
onMounted(()=>{s.connect();s.loadState();s.loadTournament()})
</script>
<template><div class="public-page"><header class="public-hero"><div class="cup">🏆</div><div><small>OFFICIAL TOURNAMENT CENTER</small><h1>ฟุตบอลเฉลิมพระเกียรติ</h1><p>ครั้งที่ 13/2569 • {{s.division.name}}</p></div><select v-model="s.divisionKey" @change="s.setDivision(s.divisionKey)"><option value="PUBLIC">รุ่นประชาชน</option><option value="SENIOR40">รุ่นอาวุโส 40+</option></select></header><main class="public-content"><section><div class="section-title"><h2>ผลแบ่งสาย</h2><span>LIVE</span></div><div class="group-grid"><GroupCard name="A" :teams="s.groups.A"/><GroupCard name="B" :teams="s.groups.B"/><GroupCard name="C" :teams="s.groups.C"/><GroupCard name="D" :teams="s.groups.D"/></div></section><div class="public-match-columns"><section><div class="section-title"><h2>โปรแกรมการแข่งขัน</h2></div><div class="public-fixtures"><article v-for="match in upcoming" :key="match.id"><header><span>{{match.group?'สาย '+match.group:'รอบ '+match.stage}}</span><time>{{dateTime(match.kickoffAt)}}</time></header><div><span><img v-if="match.home.logoUrl" :src="match.home.logoUrl" alt=""><b>{{match.home.name}}</b></span><strong>VS</strong><span><img v-if="match.away.logoUrl" :src="match.away.logoUrl" alt=""><b>{{match.away.name}}</b></span></div><footer>{{match.field||'รอกำหนดสนาม'}}</footer></article><p v-if="!upcoming.length" class="muted">ยังไม่มีโปรแกรมการแข่งขัน</p></div></section><section><div class="section-title"><h2>ผลการแข่งขันล่าสุด</h2></div><div class="score-cards public-results"><article v-for="match in results" :key="match.id"><small>{{match.stage}} {{match.group?'• สาย '+match.group:''}}</small><div><b>{{match.home.name}}</b><strong>{{match.homeScore}} - {{match.awayScore}}</strong><b>{{match.away.name}}</b></div></article><p v-if="!results.length" class="muted">ยังไม่มีผลการแข่งขัน</p></div></section></div></main></div></template>
