<script setup lang="ts">
import {computed,onMounted,ref} from 'vue'
import TopBar from '../components/TopBar.vue'
import {api} from '../stores/tournament'
import type {DivisionKey,OfficialScheduleEntry} from '../lib/types'
const schedule=ref<OfficialScheduleEntry[]>([]),division=ref<'ALL'|DivisionKey>('ALL'),stage=ref('ALL'),loading=ref(true)
const rows=computed(()=>schedule.value.filter(item=>(item.status==='FINISHED'||item.status==='LIVE')&&(division.value==='ALL'||item.divisionKey===division.value)&&(stage.value==='ALL'||item.stage===stage.value)).sort((a,b)=>b.sequenceNo-a.sequenceNo))
const dateTime=(value:string)=>new Date(value).toLocaleString('th-TH',{day:'numeric',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit',hour12:false,timeZone:'Asia/Bangkok'})
const stageTitle=(item:OfficialScheduleEntry)=>item.stage==='GROUP'?`รอบแบ่งกลุ่ม สาย ${item.groupLabel}`:item.stage==='QF'?'รอบ 8 ทีม':item.stage==='SF'?'รอบรองชนะเลิศ':item.stage==='FINAL'?'รอบชิงชนะเลิศ':'คู่พิเศษ'
onMounted(async()=>{try{schedule.value=await fetch(`${api}/api/schedule`).then(r=>r.json())}finally{loading.value=false}})
</script>
<template><div class="page public-hub-page"><TopBar/><main class="content public-hub-content"><header class="hub-heading"><div><div class="eyebrow">OFFICIAL RESULTS</div><h1>ผลการแข่งขัน</h1><p>ผลและสถานะการแข่งขันล่าสุดของทั้งสองรุ่น</p></div><div class="result-filters"><label><span>รุ่น</span><select v-model="division"><option value="ALL">ทั้งหมด</option><option value="PUBLIC">ประชาชน</option><option value="SENIOR40">อาวุโส 40+</option></select></label><label><span>รอบ</span><select v-model="stage"><option value="ALL">ทุกรอบ</option><option value="GROUP">แบ่งกลุ่ม</option><option value="QF">8 ทีม</option><option value="SF">รองชนะเลิศ</option><option value="FINAL">ชิงชนะเลิศ</option><option value="SPECIAL">คู่พิเศษ</option></select></label></div></header><div v-if="loading" class="public-empty">กำลังโหลดผลการแข่งขัน...</div><div v-else-if="!rows.length" class="public-empty"><b>ยังไม่มีผลการแข่งขัน</b><p>เมื่อแอดมินยืนยันผล รายการจะแสดงที่หน้านี้ทันที</p><RouterLink class="btn" to="/matches">ดูตารางแข่งขัน</RouterLink></div><section v-else class="results-list"><article v-for="item in rows" :key="item.id"><header><span>คู่ที่ {{item.sequenceNo}} • {{item.categoryLabel}}</span><b>{{stageTitle(item)}}</b><time>{{dateTime(item.startsAt)}}</time></header><div><RouterLink v-if="item.home.id" :to="`/teams/${item.divisionKey}/${item.home.id}`">{{item.home.name}}</RouterLink><b v-else>{{item.home.name}}</b><strong>{{item.homeScore}} – {{item.awayScore}}</strong><RouterLink v-if="item.away.id" :to="`/teams/${item.divisionKey}/${item.away.id}`">{{item.away.name}}</RouterLink><b v-else>{{item.away.name}}</b></div><footer>{{item.status==='LIVE'?'● กำลังแข่งขัน':'จบการแข่งขัน'}} • {{item.field}}</footer></article></section></main></div></template>
